### ISSUE TITLE
problemes parsing

### ISSUE THREAD

**Issue by Antoinecousi** [S-Stanley/cub-3D#70]
NO ./assets/texture_no.xpm
SO ./assets/texture_so.xpm
WE ./assets/texture_we.xpm

EA ./assets/texture_ea.xpm

F            220         ,       100,0,11

C 22225,0,0

	
111111111111111111111 1111111111111111    
1E0000000000000000000 000111111111111111
100000000000000000000000111111111111111
100000000000000000000000111111111111111
100000111110000101010000111111111111111
100000100010000000000000111111111111111
100000100010000100010000111111111111111
100000100010000000000000111111111111111
100000110110000101010000111111111111111
100000000000000000000000111111111111111
100000000000000000000000111111111111111
100000000000000000000000111111111111111
100000000000S00000000000111111111111111
100000000000000000000000111111111111111
100000000000000000000000111111111111111
100000000000000000000000111111111111111
111111111000000000000000111111111111111
110100001000000000000000111111111111111
110000101000000000000000111111111111111
110100001000000000000000111111111111111
110111111000000000000000111111111111111
110000000000000000000000111111111111111
111111111000000000000000111111111111111
111111111000000000000000111111111111111
11111111111111111111111 111111111111111

**Comment by Antoinecousi** [comment]
ttes les erreurs sont la normalement (si on ajoute les \n en fin de map + leak de 2 dans le cas dune erreur

**Comment by Antoinecousi** [comment]
Plusieurs positions joueurs avec differents points cardinaux sont possibles aussi !!

**Comment by S-Stanley** [comment]
- [ ] La couleur de doit pas depasser 255
- [ ] On devrait pas pouvoir rajouter des char apres la couleur (virgules par exemple)
- [ ] On ne devrait pas pouvoir mettre deux positions de joueurs sur la carte (genre E puis N)
- [ ] Leak de 2 quand ligne vide au milieu de la map
- [ ] New empty line a la fin de la map est compter comme erreur
