### ISSUE TITLE
Segfault espace 2

### ISSUE THREAD

**Issue by S-Stanley** [S-Stanley/cub-3D#81]
Segfault si espace dans la dernière ligne

**Comment by Antoinecousi** [comment]
111111111111111111111111
100000000000000000000001
100000000000000000000001
100000000010000000000001
100000000010000000000001
100000000000000000000001
100000000010000000000001
100000000010000000000001
100001111110000000000001
100000000000000000000001
100000000000000000000001
100000N00000011000000001
100000000000001000000001
100000000000000000000001
100000000000000000000001
100000000000000000000001
100000000000000000000001
100000000000000000000001
100000000000000000000001
100000000000000000000001
100000000000000000000001
100000000000000000000001
111011111111111111111111
1111111111111111111
11111

**Comment by Antoinecousi** [comment]
ca ca segfault aussi avec une ligne en plus apres
