### ISSUE TITLE
replace the blanks

### ISSUE THREAD

**Issue by Antoinecousi** [S-Stanley/cub-3D#85]
Si on a du blank dans la carte et que cest ferme ca s'execute (normal), mais en fait les espaces deviennent des murs invisibles. Du coup je me suis dit que pour regler la majeure partie des probleme on peut passer par un dernier traitement de carte qui pour chaque espace rencontre regarde recursivement (en etoile) si il finit par toucher un 0. Auquel cas l'espace devient une '0'

**Comment by Antoinecousi** [comment]
Ou alors faire des checks supplementaire et si et seulement si la carte est bonne, changer les esapces en '0'?

**Comment by S-Stanley** [comment]
La version 1 me parait plus rigoureuse et la version 2 me parait plus rapide. Je vais voir en fonction du temps que prends pour closer les autres issues.

**Comment by S-Stanley** [comment]
@Antoinecousi
